entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  metrics:
    address: ":8082"
  c1540:
    address: ":1540"
  c1541:
    address: ":1541"
  prom:
    address: ":9090"
  graf:
    address: ":9000"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /custom
    watch: true
certificatesResolvers:
  letsEncrypt:
    acme:
      email: postmaster@mcs-spb.com
      storage: acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: http
api:
  dashboard: true
metrics:
  prometheus:
    entryPoint: metrics

